input:
  surface:
  - mean_sea_level_pressure
  - 10m_u_component_of_wind
  - 10m_v_component_of_wind
  - 2m_temperature
  high:
  - geopotential
  - specific_humidity
  - temperature
  - u_component_of_wind
  - v_component_of_wind
  levels:
  - 1000
  - 925
  - 850
  - 700
  - 600
  - 500
  - 400
  - 300
  - 250
  - 200
  - 150
  - 100
  - 50
