- config:
    lr: 4e-5
    num_epochs: 300
    seed: 42
    batch_size: 4
    num_workers: 8
    in_channels: 69
    out_channels: 10
    mul_channels: 96
    filenames: '../data/meta/train_pangu_24.npy'
    fake: True
    log_time: 1222
